server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://blogpostdatabase.coytav0m7ktk.us-east-2.rds.amazonaws.com:3306/blogpost
    username: root
    password: akhilcharugulla
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect